library(tidyverse)
library(openxlsx)

setwd("Y:/MFO_Privat/MG/MOCIS/MCOM/R/MCOM20_data/")

data_path <- "../MCOM20_data/clean_data/full_data_2019.csv"

full_data <- read_csv(data_path, guess_max = 100000) 

filter_species <- function(data, x){
  if (str_detect(x, "uria"))
  { filter(data, GENUS %in% c("SIGR", "STER", "HAEM"))}
  else
  { filter(data, GENUS %in% c("CLUP", "GADU", "MYTI", "PERC", "ZOAR"))}
}

file_names <- c("havbfr.xlsx", "havbio.xlsx", "havclc.xlsx", "havdx.xlsx", 
                "havmet.xlsx", "havpah.xlsx", "havpfc.xlsx", "havto.xlsx", "uriabfr.xlsx", 
                "uriaclc.xlsx", "uriadx.xlsx", "uriamet.xlsx", "uriapfc.xlsx")

# List of variables generated by dput on 
#
# map(file_names, ~read_excel(paste0("data/", .x), n_max = 0) %>% names() %>% ifelse((. == "FPRC*"), ., str_remove(.,"\\*"))) %>% 
#   map(~str_replace(.x, "^LPFDS.{5}", "LPFDS") %>% unique() %>% subset(!(. == "BDE-209")))
#
# where "data/" contains a collection of excel-files required by MoCiS

variables <- list(c("YWD", "ACCNR", "GENUS", "LOC", "LOKAL", "NKOO", "EKOO", 
                    "SEX", "NHOM", "TOTL", "TOTV", "ALDR", "FPRC", "MTPRC", "BDE-47", 
                    "BDE-99", "BDE-100", "BDE-153", "BDE-154", "HBCD", "BDE-28"), 
                  c("YWD", "ACCNR", "GENUS", "LOC", "LOKAL", "NKOO", "EKOO", 
                    "SEX", "NHOM", "TOTL", "TOTV", "ALDR", "FPRCU", "FPRC", "FPRCPP", 
                    "FPRC*", "MTPRC", "LTPRC", "LVKT", "D13CUCD", "CUCD", "D15NUCD", 
                    "NUCD"), 
                  c("YWD", "ACCNR", "GENUS", "LOC", "LOKAL", "NKOO", 
                    "EKOO", "SEX", "NHOM", "TOTL", "TOTV", "ALDR", "FPRC*", "MTPRC", 
                    "LVKT", "DDE", "DDD", "DDT", "DDTSNY", "PCBSUM", "PCB8", 
                    "PCB10", "DDEK", "DDDK", "DDTK", "DDTSH", "LINDA", "AHCH", 
                    "BHCH", "HCB", "CB-28", "CB-52", "CB-101", "CB-118", "CB-153", 
                    "CB-138", "CB-180", "FPRC", "D13CUCD", "CUCD", "D15NUCD", 
                    "NUCD"), 
                  c("YWD", "ACCNR", "GENUS", "LOC", "LOKAL", "NKOO", 
                    "EKOO", "SEX", "NHOM", "TOTL", "TOTV", "ALDR", "FPRCU", "FPRC", 
                    "FPRCPP", "FPRC*", "TCDD", "PECDD", "HXCDD1", "HXCDD2", "HXCDD3", 
                    "HPCDD", "OCDD", "TCDF", "PECDF1", "PECDF2", "HXCDF1", "HXCDF2", 
                    "HXCDF3", "HXCDF4", "HPCDF1", "HPCDF2", "OCDF", "CB-77", 
                    "CB-81", "CB-126", "CB-169", "CB-105", "CB-114", "CB-118U", 
                    "CB-123", "CB-156", "CB-157", "CB-167", "CB-189", "TCDDEQV", 
                    "CBEQV", "TCDDEQ05", "CBEQ05"), 
                  c("YWD", "ACCNR", "GENUS", 
                    "LOC", "LOKAL", "NKOO", "EKOO", "SEX", "NHOM", "TOTL", "TOTV", 
                    "ALDR", "FPRC", "MTPRC", "LTPRC", "LVKT", "HGFS", "HGFSI", 
                    "PBTS", "PBTSI", "CDTS", "CDTSI", "CUTS", "CUTSI", "ZNTS", 
                    "ZNTSI", "NITS", "NITSI", "CRTS", "CRTSI", "AGTSI", "ASTSI", 
                    "ALTSI", "FPRCP", "TPRC", "MTPRCI", "SETSI", "SNTSI"), 
                  c("YWD", 
                    "ACCNR", "GENUS", "LOC", "LOKAL", "NKOO", "EKOO", "SEX", 
                    "NHOM", "TOTL", "TOTV", "ALDR", "FPRC*", "MTPRC", "LVKT", 
                    "NAP", "ACNE", "FLE", "PA", "ANT", "FLU", "PYR", "BAA", "CHR", 
                    "BBF", "BKF", "BAP", "DBAHA", "BGHIP", "ICDP", "SUMPAH", 
                    "TPRC"), 
                  c("YWD", "ACCNR", "GENUS", "LOC", "LOKAL", "NKOO", 
                    "EKOO", "SEX", "NHOM", "TOTL", "TOTV", "ALDR", "LTPRC", "PFHXA", 
                    "PFHPA", "PFOA", "PFNA", "PFDA", "PFUNDA", "PFDODA", "PFTRDA", 
                    "PFTEDA", "PFPEDA", "LPFBS", "PFHXS", "PFOS", "PFDS", "FOSA", 
                    "LFOSA", "BFOSA", "LPFOS", "BPFOS", "LPFDS"), 
                  c("YWD", "ACCNR", 
                    "GENUS", "LOC", "LOKAL", "NKOO", "EKOO", "SEX", "NHOM", "TOTL", 
                    "TOTV", "ALDR", "FPRC*", "MTPRC", "LVKT", "MBT", "DIBT", 
                    "TBT", "MPT", "DIPT", "TPT", "MOT", "DIOT"), 
                  c("YWD", "ACCNR", 
                    "GENUS", "LOC", "LOKAL", "NKOO", "EKOO", "SEX", "NHOM", "TOTL", 
                    "TOTV", "ALDR", "FPRC", "MTPRC", "BDE-47", "BDE-99", "BDE-100", 
                    "BDE-153", "BDE-154", "HBCD", "BDE-28"), 
                  c("YWD", "ACCNR", 
                    "GENUS", "LOC", "LOKAL", "GRU", "NKOO", "EKOO", "NHOM", "TOTL", 
                    "TOTV", "FPRC", "MTPRC", "DDE", "DDD", "DDT", "DDTSNY", "PCBSUM", 
                    "PCB8", "PCB10", "DDEK", "DDDK", "DDTK", "DDTSH", "LINDA", 
                    "AHCH", "BHCH", "HCB", "CB-28", "CB-52", "CB-101", "CB-118", 
                    "CB-153", "CB-138", "CB-180", "D13CUCD", "CUCD", "D15NUCD", 
                    "NUCD"), 
                  c("YWD", "ACCNR", "GENUS", "LOC", "LOKAL", "GRU", 
                    "NKOO", "EKOO", "SEX", "NHOM", "TOTL", "TOTV", "ALDR", "FPRCU", 
                    "TCDF", "PECDF1", "PECDF2", "HXCDF1", "HXCDF2", "HXCDF3", 
                    "HXCDF4", "HPCDF1", "HPCDF2", "OCDF", "TCDD", "PECDD", "HXCDD1", 
                    "HXCDD2", "HXCDD3", "HPCDD", "OCDD", "CB-77", "CB-81", "CB-126", 
                    "CB-169", "CB-123", "CB-118U", "CB-114", "CB-105", "CB-167", 
                    "CB-156", "CB-157", "CB-189", "TCDDEQV", "CBEQV", "TCDDEQ05", 
                    "CBEQ05"), 
                  c("YWD", "ACCNR", "GENUS", "LOC", "LOKAL", "GRU", 
                    "NKOO", "EKOO", "SEX", "NHOM", "TOTL", "TOTV", "ALDR", "FPRC", 
                    "MTPRC", "LTPRC", "LVKT", "HGFS", "HGFSI", "PBTS", "PBTSI", 
                    "CDTS", "CDTSI", "CUTS", "CUTSI", "ZNTS", "ZNTSI", "NITS", 
                    "NITSI", "CRTS", "CRTSI", "AGTSI", "ASTSI", "ALTSI", "HGFST", 
                    "SETSI", "SNTSI"), 
                  c("YWD", "ACCNR", "GENUS", "LOC", "LOKAL", 
                    "GRU", "NKOO", "EKOO", "SEX", "NHOM", "TOTL", "TOTV", "ALDR", 
                    "TPRC", "PFHXA", "PFHPA", "PFOA", "PFNA", "PFDA", "PFUNDA", 
                    "PFDODA", "PFTRDA", "PFTEDA", "PFPEDA", "LPFBS", "PFHXS", 
                    "PFOS", "PFDS", "FOSA", "LFOSA", "BFOSA", "LPFOS", "BPFOS", 
                    "LPFDS"))

# Splits data according to variables and saves as excel-files named file_names

walk2(file_names, variables, ~select(full_data, .y) %>% 
        filter_species(.x) %>% 
        write.xlsx(file = paste0("Y:/MFO_Privat/MG/MOCIS/MCOM/R/MCOM20_MoCiS/MoCiS_data/", .x))
      # write.xlsx(file = paste0("Y:/MFO_Privat/MG/Milj?gifts?vervakning/MCOM/MCOM2020/R/MCOM20_MoCiS/MoCiS_data/", .x))
)

