# Runs mocis on excel-files generated by prepare_data.R
library(MoCiS)
#setwd("Y:/MFO_Privat/MG/Milj?gifts?vervakning/MCOM/MCOM2020/R/MCOM20_MoCiS/")
setwd("Y:/MFO_Privat/MG/MOCIS/MCOM/R/MCOM20_MoCiS/")

havbio <- mocis(file = "MoCiS_data/havbio.xlsx", vars = c("ALDR", "TOTV", "TOTL", "KOND"), agesel = NULL)
havmet <- mocis(file = "MoCiS_data/havmet.xlsx", vars = c('HG',	'PB',	'CD',	'CU',	'ZN',	'NI',	'CR',	'AG',	'AS',	'AL','SE'), agesel = NULL, fat_adj = NULL)
havclc <- mocis(file = "MoCiS_data/havclc.xlsx", vars = c('PCBSUM','CB28', 'CB52', 'CB101', 'CB138', 'CB180','CB153','CB118','FPRC'), agesel = NULL, fat_adj = NULL)
havclc2 <- mocis(file = "MoCiS_data/havclc.xlsx", vars = c('DDE','DDD','DDT', 'AHCH','BHCH','LINDA','HCB','FPRC'), agesel = NULL, fat_adj = NULL)
havbfr <- mocis(file = "MoCiS_data/havbfr.xlsx", vars = c('BDE47','BDE99','BDE100','BDE153','BDE154','HBCD','BDE28'), agesel = NULL)
havpfc <- mocis(file = "MoCiS_data/havpfc.xlsx", vars = c('PFHXA',	'PFHPA'	,'PFOA'	,'PFNA'	,'PFDA'	,'PFUNDA'	,'PFDODA',	'PFTRDA',	'PFTEDA',	'PFPEDA',	'LPFBS',	'PFHXS',	'PFOS',	
                                                        'PFDS',	'FOSA','LFOSA',	'BFOSA',	'LPFOS',	'BPFOS',	'LPFDS'), agesel = NULL)
havdx <- mocis(file = "MoCiS_data/havdx.xlsx", vars = c('TCDF',	'PECDF1',	'PECDF2',	'HXCDF1',	'HXCDF2',	'HXCDF3'	,'HXCDF4',	'HPCDF1',	'HPCDF2'	,'OCDF'	,'TCDD'	,'PECDD'	,
                                                      'HXCDD1',	'HXCDD2',	'HXCDD3',	'HPCDD',	'OCDD'	,'CB77',	'CB81',	'CB126',	'CB169',	'CB123',	'CB114'	,
                                                      'CB105'	,'CB167',	'CB156',	'CB157',	'CB189',	'TCDDEQV',	'CBEQV', "TCDDEQ05", "CBEQ05"), agesel = NULL)
havpah <- mocis(file = "MoCiS_data/havpah.xlsx", vars = c('SUMPAH', 'NAP', 'ACNE', 'FLE', 'PA', 'ANT', 'FLU', 'PYR', 'BAA', 'CHR', 'BBF', 'BKF', 'BAP', 'BGHIP', 'DBAHA', 'ICDP'), agesel = NULL)
havto <- mocis(file = "MoCiS_data/havto.xlsx", vars = c("MBT", "DIBT", "TBT", "MPT", "DIPT", "TPT", "MOT", "DIOT"), agesel = NULL)
uriabfr <- mocis(file = "MoCiS_data/uriabfr.xlsx", vars = c('BDE47','BDE99','BDE100','BDE153','BDE154','HBCD','BDE28'), agesel = NULL)
uriaclc <- mocis(file = "MoCiS_data/uriaclc.xlsx", vars = c('PCBSUM','CB28', 'CB52', 'CB101', 'CB138', 'CB180','CB153','CB118','FPRC'), agesel = NULL)
uriaclc2 <- mocis(file = "MoCiS_data/uriaclc.xlsx", vars = c('DDE','DDD','DDT', 'AHCH','BHCH','LINDA','HCB','FPRC'), agesel = NULL)
uriadx <- mocis(file = "MoCiS_data/uriadx.xlsx", vars = c('TCDF',	'PECDF1',	'PECDF2',	'HXCDF1',	'HXCDF2',	'HXCDF3'	,'HXCDF4',	'HPCDF1',	'HPCDF2'	,'OCDF'	,'TCDD'	,'PECDD'	,
                                                        'HXCDD1',	'HXCDD2',	'HXCDD3',	'HPCDD',	'OCDD'	,'CB77',	'CB81',	'CB126',	'CB169',	'CB123',	'CB114'	,
                                                        'CB105'	,'CB167',	'CB156',	'CB157',	'CB189',	'TCDDEQV',	'CBEQV', "TCDDEQ05", "CBEQ05"), agesel = NULL)
uriamet <- mocis(file = "MoCiS_data/uriamet.xlsx", vars = c('HG',	'PB',	'CD',	'CU',	'ZN',	'NI',	'CR',	'AG',	'AS',	'AL','SE'), agesel = NULL)
uriapfc <- mocis(file = "MoCiS_data/uriapfc.xlsx", vars = c('PFHXA',	'PFHPA'	,'PFOA'	,'PFNA'	,'PFDA'	,'PFUNDA'	,'PFDODA',	'PFTRDA',	'PFTEDA',	'PFPEDA',	'LPFBS',	'PFHXS',	'PFOS',	 'PFDS',	'FOSA','LFOSA',	'BFOSA',	'LPFOS',	'BPFOS',	'LPFDS'), agesel = NULL)

mocis_all <- list(havbio = havbio, havmet = havmet, havdx = havdx, havclc = havclc, havclc2 = havclc2, havbfr = havbfr, havpfc =  havpfc, havpah = havpah, havto = havto,
                  uriabfr = uriabfr, uriaclc = uriaclc, uriaclc2 = uriaclc2, uriadx = uriadx,  uriapfc = uriapfc, uriamet = uriamet)
save(mocis_all, file = "mocis_all.Rdata")
